openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
paths:
  /api/v1/categories:
    get:
      tags:
        - Categories
      summary: Return a list of categories
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: 
                          type: number
                          example: '1'
                        name: 
                          type: string
                          example: 'Vinhos'
                        description: 
                          type: string
                          example: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
                        created_at: 
                          type: string
                          example: '2023-12-16T02:17:49.951+00:00'
                        updated_at: 
                          type: string
                          example: '2023-12-16T02:17:49.951+00:00'
                  meta: 
                    type: object
                    properties:
                      total:
                        type: number
                        example: 10           

  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                  example: 'teste@gmail.com'
                password: 
                  type: string
                  example: '12345'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: 'bearer'
                  token:
                    type: string
                    example: 'MQ.u-ouhSHrhl3fxfIUcpN3NArnzqo-fye_m9'
                  expires_at:
                    type: string
                    example: '2023-12-26T02:17:53.507+00:0'
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: 'required validation failed"'
        '422':
          description: Missing required fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: array
                    items:
                      type: object
                      properties:
                        rule:
                          type: string
                          example: 'required'
                        required:
                          type: string
                          example: 'password'
                        message:
                          type: string
                          example: 'required validation failed"'

  /api/v1/drinks/{id}:
    get:
      tags:
        - Drinks
      summary: Drink by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: number
                    example: 1
                  name: 
                    type: string
                    example: 'Old Parr'
                  description: 
                    type: string
                    example: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
                  category_id: 
                      type: number
                      example: 1
                  created_at: 
                    type: string
                    example: '2023-12-16T02:17:49.951+00:00'
                  updated_at: 
                    type: string
                    example: '2023-12-16T02:17:49.951+00:00'
  
  /api/v1/drinks:
    get:
      tags:
        - Drinks
      summary: Drinks
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: 
                          type: number
                          example: 1
                        name: 
                          type: string
                          example: 'Old Parr'
                        description: 
                          type: string
                          example: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
                        category_id: 
                            type: number
                            example: 1
                        created_at: 
                          type: string
                          example: '2023-12-16T02:17:49.951+00:00'
                        updated_at: 
                          type: string
                          example: '2023-12-16T02:17:49.951+00:00'
                  meta:
                    type: object
                    properties:
                      total:
                        type: number
                        example: 10

  /api/v1/category/{id}/drinks:
    get:
      tags:
        - Drinks
      summary: Drinks by Category
      parameters:
        - in: path
          name: categoryId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: 
                          type: number
                          example: 1
                        name: 
                          type: string
                          example: 'Old Parr'
                        description: 
                          type: string
                          example: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
                        category_id: 
                            type: number
                            example: 1
                        created_at: 
                          type: string
                          example: '2023-12-16T02:17:49.951+00:00'
                        updated_at: 
                          type: string
                          example: '2023-12-16T02:17:49.951+00:00'
                  meta:
                    type: object
                    properties:
                      total:
                        type: number
                        example: 10
  
  /api/v1/favorites/{id}:
    delete:
      tags:
        - Favorites
      summary: Delete a favorite drink
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        204:
          description: No Content
  
  /api/v1/favorites:
    get:
      tags:
        - Favorites
      security:
        - BearerAuth: []
      summary: Favorites drinks of the logged user
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: 
                          type: number
                          example: 1
                        name: 
                          type: string
                          example: 'Old Parr'
                        description: 
                          type: string
                          example: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
                        category_id: 
                            type: number
                            example: 1
                        created_at: 
                          type: string
                          example: '2023-12-16T02:17:49.951+00:00'
                        updated_at: 
                          type: string
                          example: '2023-12-16T02:17:49.951+00:00'
                  meta:
                    type: object
                    properties:
                      total:
                        type: number
                        example: 10

    post:
      tags:
        - Favorites
      summary: Bookmark a drink
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                drink_id: 
                  type: string
                  example: '1'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: number
                    example: 1
                  name: 
                    type: string
                    example: 'Cerveja'
                  description: 
                    type: string
                    example: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
                  category_id: 
                    type: number
                    example: 1
                  created_at: 
                    type: string
                    example: '2023-12-16T02:17:49.951+00:00'
                  updated_at: 
                    type: string
                    example: '2023-12-16T02:17:49.951+00:00'
        422:
          description: Missing required fields
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: array
                    items:
                      type: object
                      properties:
                        rule:
                          type: string
                          example: 'required'
                        required:
                          type: string
                          example: 'password'
                        message:
                          type: string
                          example: 'required validation failed"'